version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: karyavaani-backend
    ports:
      - "3241:3241"
    environment:
      - PORT=3241
      - MAIL_HOST=smtp.office365.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=support@pionedata.com
      - EMAIL_HOST_PASSWORD=yxfczkkwrqdtsrcz
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karyavaani-frontend
    ports:
      - "3240:3240"
    depends_on:
      - backend
    restart: unless-stopped
